### ISSUE TITLE
Which zip file to download ?

### ISSUE THREAD

**Issue by nk2164** [bruderstein/nppPluginManager#147]
What is the difference between 
PluginManager_v1.4.12_x64.zip & PluginManager_v1.4.12_x64_PA.zip

I have a NPP with 64 bit on windows . Which one should i use ? Thanks.

**Comment by chcg** [comment]
@nk2164 Which version of N++ do you use? In case it is newer than 7.6.x you should use the builtin PluginAdmin, because PluginManager doesn't fully support the change in the N++ plugin folder structure.

PluginManager_v1.4.12_x64_PA.zip is the same as PluginManager_v1.4.12_x64.zip, but doesn't contain the update component gpup. The package was used for the PluginAdmin plugin list.

**Comment by nk2164** [comment]
@chcg , thank you for that clarification. Mine is newer than 7.6 . Will use the PluginAdmin.
