### ISSUE TITLE
Crash if no Internet is available and plugin Installation is tried

### ISSUE THREAD

**Issue by RedX2501** [bruderstein/nppPluginManager#3]
When trying to install a plugin without internet connection the plugin will crash notepad++.

**Comment by ryancu7** [comment]
Similarly, Notepad++ crashes if Internet is available but download servers don't return success.

For example, the company I work for blocks sourceforge.net (all requests get a 403 error page) due to their [adware practices](http://www.lifehacker.com.au/2015/06/notepad-and-pale-moon-leave-sourceforge-over-adware-practices/). When the Notepad++ plugin manager notifies me that a plugin needs updating (e.g. NppFtp) and I click update, Notepad++ crashes as soon as it tries to start downloading the plugin.

Problem Event Name: APPCRASH
Application Name: notepad++.exe
Application Version: 6.9.2.0
Fault Module Name: PluginManager.dll
Fault Module Version: 1.3.5.0

**Comment by bruderstein** [comment]
Can you try installing 1.4.1 from the releases section manually - there were some improvements made around connectivity issues (and also it doesn't use sourceforge any more!)

**Comment by RedX2501** [comment]
Where is the releases section? http://www.brotherstone.co.uk/npp/pm/#download only has link to outdated versions...

**Comment by bruderstein** [comment]
Just click the releases link shown in @sm4rk0 message - https://github.com/bruderstein/nppPluginManager/releases

**Comment by RedX2501** [comment]
I did that. I just wanted to point out that it is not visible to me (everyone?).

**Comment by bruderstein** [comment]
Ok, cool, glad to know you found it!

Just checked on a logged-out window, and it's there for me
![releases](https://cloud.githubusercontent.com/assets/91716/19289284/521845f0-900a-11e6-911f-bd1407d70bde.png)

**Comment by bruderstein** [comment]
Closing as no further response. If this is still an issue, feel free to reopen
